# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.145.1/containers/javascript-node/.devcontainer/base.Dockerfile

#FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-14-buster
FROM node:14-buster