name: Publish
on:
  push:
    branches:
      - "master"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build content
        run: |
          yarn
          yarn build
      - uses: redkubes/docusaurus-deploy-action@v1.2
        with:
          source-folder: build
          git-user: ${{ github.actor }}
          git-password: ${{ secrets.GITHUB_TOKEN }}